order-for-manager
alexanderyar/hedgehog-backend pull request #12
Opened 2023-05-30 00:03 UTC by alexanderyar

2023-05-30 17:36 UTC, KossGuk requested changes

2023-05-30 17:36 UTC, KossGuk commented on migrations/1685395695725--addCompanyNameAndClientType.ts
> +        type: "varchar",
It should be enum.
As example: 1683263331830-Initial.ts:21

2023-05-30 17:36 UTC, KossGuk commented on migrations/1685397841630--movingCountryToClients.ts
> +      "UPDATE clients SET country = users.country FROM users WHERE clients.user_id = users.id"
Good job :)

2023-05-30 17:36 UTC, KossGuk commented on migrations/1685398369056--dropCountryUsers.ts
> +    await queryRunner.query("ALTER TABLE users DROP COLUMN country");
It's not a blocker.
It could be done in the same migration as migrations/1685397841630--movingCountryToClients.ts

2023-05-31 01:07 UTC, alexanderyar commented on migrations/1685398369056--dropCountryUsers.ts
> +    await queryRunner.query("ALTER TABLE users DROP COLUMN country");
I do realize that. The reason behind it was to break down changes in a table so if anything goes wrong I know exactly at what point that happened

2023-05-31 01:14 UTC, alexanderyar commented on migrations/1685397841630--movingCountryToClients.ts
> +      "UPDATE clients SET country = users.country FROM users WHERE clients.user_id = users.id"
<img width="381" alt="Screen Shot 2023-05-30 at 19 13 26" src="https://github.com/alexanderyar/hedgehog-backend/assets/103504393/ec3469a4-2648-4310-9bf2-3f773485a3c4">

2023-05-31 02:40 UTC, KossGuk requested changes

2023-05-31 02:40 UTC, KossGuk commented on src/entity/Client.entity.ts
> +  type: string;
Here Enum as well.

2023-05-31 18:40 UTC, KossGuk approved these changes

2023-05-31 18:40 UTC, merged